services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "mnt"
      USER: "bjtn"
      PASS: "${PASS}"
      UID: "1000"
      GID: "1000"
    ports:
      - 445:445
    volumes:
      #- ./samba:/storage
      - /mnt:/storage
      # overrides fruit:metadata to netatalk mode -- see comment in the file
      - ./smb.conf:/etc/samba/smb.conf:ro
    restart: unless-stopped
