services:
  stage-control:
    build: .
    container_name: stage-control
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - /mnt/vault:/mnt/vault
    networks:
      - bjtn-proxy

networks:
  bjtn-proxy:
    external: true
