#!/usr/bin/env python3
"""
Phone-friendly panel for granting/revoking which apps each person can reach, sitting on
top of Authelia's access control. Same shape as arr-control/downloads-control: one page,
big buttons, no framework.

This app owns exactly ONE file: /authelia/access.yml (bind-mounted as a single file, not
the whole Authelia config directory -- it can never touch users_database.yml, the session
secret, or the SQLite db). Authelia does NOT hot-reload its config (confirmed: a real,
documented limitation, not an oversight), so a rule change needs a restart to take effect.
Rather than hand this container the real Docker socket, it talks to a narrowly-scoped
docker-socket-proxy sidecar that can only restart containers -- no exec, no images, no
volumes -- reached over an internal-only network nothing else can touch.

GRANTABLE is a hardcoded allowlist, not derived from the Caddyfile -- so this panel can
never expose an app (Arcane, Prowlarr, etc.) that wasn't deliberately added here first.
Adding a brand-new PERSON (an Authelia account with a password) is a separate, rarer,
one-time step done directly in users_database.yml -- this panel only toggles which apps an
EXISTING account can reach. It DOES read users_database.yml (mounted read-only, a second
single-file mount alongside access.yml) to offer a real, type-to-search pick-list of actual
accounts, so "add a person" can't silently create a rule for a login that doesn't exist.
"""
import json
import os
import re
import urllib.error
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

import yaml

STATE = "/state/access.json"
RULES_OUT = "/authelia/access.yml"
USERS_DB = "/authelia/users_database.yml"  # read-only mount -- this app can only READ it,
                                            # never write; adding a brand-new login is still
                                            # a separate, deliberate step done on the server.
ADMIN_USER = os.environ.get("ADMIN_USER", "bjtn")
DOCKER_PROXY_URL = os.environ.get("DOCKER_PROXY_URL", "")

# The only apps this panel is allowed to ever grant. Add a line here deliberately when you
# decide an app is safe to ever hand to someone else; nothing reachable through this page
# that isn't listed here.
GRANTABLE = [
    ("Jellyfin", "jellyfin.bjtn.xyz"),
    ("Nextcloud", "nextcloud.bjtn.xyz"),
    ("Jellyseerr", "seerr.bjtn.xyz"),
    ("Immich", "photos.bjtn.xyz"),
]

NAME_RE = re.compile(r"^[a-z][a-z0-9_-]{0,31}$")


def load():
    try:
        with open(STATE, encoding="utf-8") as f:
            return json.load(f)
    except (OSError, ValueError):
        return {}


def real_users():
    """Every actual Authelia login (read-only), so the panel only ever offers picking from
    accounts that really exist -- never a free-typed name that silently goes nowhere."""
    try:
        with open(USERS_DB, encoding="utf-8") as f:
            doc = yaml.safe_load(f) or {}
    except (OSError, yaml.YAMLError):
        return set()
    return set((doc.get("users") or {}).keys())


def save(access):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    tmp = STATE + ".part"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(access, f, indent=1, sort_keys=True)
    os.replace(tmp, STATE)
    write_authelia_rules(access)
    restart_authelia()


def restart_authelia():
    """Rules only take effect after Authelia restarts (it doesn't watch its config files).
    Best-effort: if the proxy is down, the file is still written correctly and will apply
    on Authelia's next restart for any other reason; we don't fail the user's click over it."""
    if not DOCKER_PROXY_URL:
        return
    req = urllib.request.Request(f"{DOCKER_PROXY_URL}/containers/authelia/restart", method="POST")
    try:
        urllib.request.urlopen(req, timeout=15).read()
    except (urllib.error.URLError, OSError) as e:
        print(f"WARNING: could not restart authelia via docker-proxy: {e}", flush=True)


def write_authelia_rules(access):
    rules = [{"domain": "*.bjtn.xyz", "subject": f"user:{ADMIN_USER}", "policy": "two_factor"}]
    valid_domains = {d for _label, d in GRANTABLE}
    for person, domains in sorted(access.items()):
        for d in domains:
            if d not in valid_domains:  # defensive: never write a rule for something not on the allowlist
                continue
            rules.append({"domain": d, "subject": f"user:{person}", "policy": "two_factor"})
    doc = {"access_control": {"default_policy": "deny", "rules": rules}}
    header = (
        "# GENERATED by access-control -- do not hand-edit, changes will be overwritten "
        "on the next toggle.\n"
    )
    # RULES_OUT is a single-FILE bind mount (deliberately, so this container can never
    # create/touch anything else in Authelia's config dir) -- that means there's no
    # writable parent directory here to stage a temp file in for an atomic rename, so
    # this writes in place. The file is tiny and rewritten rarely (one button press),
    # so the truncate-then-write window is an acceptable tradeoff for the extra isolation.
    with open(RULES_OUT, "w", encoding="utf-8") as f:
        f.write(header)
        yaml.safe_dump(doc, f, sort_keys=False)


def render(access):
    people_html = ""
    for person in sorted(access):
        domains = access[person]
        btns = "".join(
            f'<button class="{"on" if dom in domains else "off"}" '
            f'formaction="/toggle?user={person}&app={dom}">{label}</button>'
            for label, dom in GRANTABLE
        )
        people_html += (
            f'<div class="person"><div class="row"><h2>{person}</h2>'
            f'<button class="remove" formaction="/remove?user={person}">remove person</button></div>'
            f'<form method="post">{btns}</form></div>'
        )
    if not access:
        people_html = '<p class="empty">Nobody has any app access yet. Add a person below.</p>'

    # pick-list = real Authelia accounts, minus the admin and anyone already listed above --
    # native <input list=...> keeps this a normal type-to-search text box (nothing removed),
    # it just also offers a dropdown of names that are guaranteed to be real accounts.
    pickable = sorted(real_users() - {ADMIN_USER} - set(access))
    options_html = "".join(f'<option value="{u}">' for u in pickable)
    if pickable:
        add_hint = "Pick an existing login, or type one below."
    else:
        add_hint = "No un-added Authelia logins found -- creating a brand-new login is still a one-time step on the server."
    return f"""<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Access</title>
<style>
  body {{ font-family: -apple-system, sans-serif; background: #111; color: #eee;
         padding: 16px; max-width: 480px; margin: 0 auto; }}
  h1 {{ font-size: 1.4rem; }}
  .person {{ margin-bottom: 28px; border-bottom: 1px solid #333; padding-bottom: 16px; }}
  .row {{ display: flex; justify-content: space-between; align-items: center; }}
  .row h2 {{ margin: 0; font-size: 1.1rem; }}
  form {{ display: flex; flex-wrap: wrap; gap: 8px; margin-top: 8px; }}
  button {{ font-size: 1.05rem; padding: 16px 18px; border-radius: 12px; border: none;
            cursor: pointer; }}
  .on  {{ background: #2e7d32; color: #fff; font-weight: 600; }}
  .off {{ background: #2a2a2a; color: #999; }}
  .remove {{ background: #4a1f1f; color: #e88; padding: 8px 14px; font-size: 0.85rem; }}
  .empty {{ color: #999; }}
  .add {{ display: flex; gap: 8px; margin-top: 24px; }}
  input {{ font-size: 1.05rem; padding: 14px; border-radius: 10px; border: 1px solid #444;
           background: #1a1a1a; color: #eee; flex: 1; min-width: 0; }}
  .addbtn {{ background: #1565c0; color: #fff; font-weight: 600; }}
  .hint {{ color: #777; font-size: 0.8rem; margin-top: 4px; }}
</style></head>
<body>
<h1>Who can reach what</h1>
{people_html}
<form method="post" class="add">
  <input name="newperson" list="known-users" placeholder="username" pattern="[a-z][a-z0-9_-]{{0,31}}" required autocomplete="off">
  <datalist id="known-users">{options_html}</datalist>
  <button class="addbtn" formaction="/add">add</button>
</form>
<p class="hint">{add_hint}
{ADMIN_USER} always has access to everything and isn't shown here.
Adding a brand-new person's login (not just toggling their apps) still needs a one-time step on the server.</p>
</body></html>"""


class Handler(BaseHTTPRequestHandler):
    def _send(self, code, body):
        self.send_response(code)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if urlparse(self.path).path != "/":
            self._send(404, b"not found")
            return
        self._send(200, render(load()).encode())

    def do_POST(self):
        path = urlparse(self.path).path
        q = parse_qs(urlparse(self.path).query)
        access = load()

        if path == "/toggle":
            user, app = q.get("user", [""])[0], q.get("app", [""])[0]
            if user in access and app in {d for _l, d in GRANTABLE}:
                cur = access[user]
                (cur.remove(app) if app in cur else cur.append(app))
                save(access)

        elif path == "/add":
            body_len = int(self.headers.get("Content-Length", 0))
            form = parse_qs(self.rfile.read(body_len).decode())
            name = form.get("newperson", [""])[0].strip().lower()
            # must be a REAL Authelia login, not just well-formed text -- otherwise this would
            # silently grant a rule for a user: subject that can never actually log in as anyone
            if NAME_RE.match(name) and name in real_users() and name != ADMIN_USER and name not in access:
                access[name] = []
                save(access)

        elif path == "/remove":
            user = q.get("user", [""])[0]
            if user in access:
                del access[user]
                save(access)

        self.send_response(303)
        self.send_header("Location", "/")
        self.end_headers()

    def log_message(self, fmt, *args):
        print(f"[{self.log_date_time_string()}] {self.address_string()} {fmt % args}", flush=True)


if __name__ == "__main__":
    if not os.path.exists(STATE):
        save({})  # first boot: seed the state file and write the matching access.yml
    print("access-control listening on :8770", flush=True)
    ThreadingHTTPServer(("0.0.0.0", 8770), Handler).serve_forever()
